ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = SYSTEM;

CREATE TABLE TARIFFS (
    TARIFF_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    MONTHLY_FEE NUMBER(10, 2),
    DATA_LIMIT NUMBER,
    MINUTE_LIMIT NUMBER,
    SMS_LIMIT NUMBER
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    CITY VARCHAR2(50),
    SIGNUP_DATE DATE,
    TARIFF_ID NUMBER,
    CONSTRAINT fk_tariff FOREIGN KEY (TARIFF_ID) REFERENCES TARIFFS(TARIFF_ID)
);

CREATE TABLE MONTHLY_STATS (
    ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    DATA_USAGE NUMBER(15, 2),
    MINUTE_USAGE NUMBER,
    SMS_USAGE NUMBER,
    PAYMENT_STATUS VARCHAR2(20), 
    CONSTRAINT fk_customer FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE INDEX idx_cust_city ON CUSTOMERS(CITY);
CREATE INDEX idx_tariff_id ON CUSTOMERS(TARIFF_ID);
